// EDIT THIS FILE to update store details, categories, brands, products and prices.
export const STORE={name:'DDM Electronics',shortName:'DDM',phone:'917617202212',displayPhone:'+91 76172 02212',email:'ddmelectronics@rediffmail.com',address:'HQCM+5F, Bhind, Madhya Pradesh',latitude:26.570557859198875,longitude:78.78421004180777,currency:'INR',locale:'en-IN'};
export const INTEGRATIONS={apiBaseUrl:'',ordersEndpoint:'/orders',useLiveOrderApi:false,whatsapp:{enabled:true,phone:'917617202212'},email:{enabled:true,address:'ddmelectronics@rediffmail.com'},instagram:{enabled:false,url:''},googleMaps:{enabled:true,url:'https://www.google.com/maps/dir/?api=1&destination=26.570557859198875%2C78.78421004180777'},payment:{enabled:false,provider:'razorpay'}};
export const ORDER_POLICY={advancePercent:20,cashOnDelivery:true,returnsAllowed:false,replacementOnly:true};
export const CATEGORIES=[
{id:'Washing Machine',label:'Washing Machines',detail:'Top load & front load',icon:'🫧'},{id:'AC',label:'Air Conditioners',detail:'Split & window ACs',icon:'❄️'},{id:'Refrigerator',label:'Refrigerators',detail:'Single & double door',icon:'🧊'},{id:'LED',label:'LED TVs',detail:'Smart, UHD & 4K',icon:'📺'},{id:'Atta Chakki',label:'Atta Chakki',detail:'Domestic flour mills',icon:'🌾'},{id:'Microwave Oven',label:'Microwave Ovens',detail:'Solo, grill & convection',icon:'♨️'},{id:'Iron',label:'Irons',detail:'Dry & steam irons',icon:'♨'},{id:'Mixer Grinder',label:'Mixer Grinders',detail:'Everyday kitchen essentials',icon:'⚙️'},{id:'Water Heater',label:'Water Heaters',detail:'Instant & storage geysers',icon:'💧'}];
export const BRANDS=[
{id:'Panasonic',name:'Panasonic',domain:'panasonic.com',detail:'Home & kitchen'},{id:'IFB',name:'IFB',domain:'ifbappliances.com',detail:'Laundry & kitchen'},{id:'Samsung',name:'Samsung',domain:'samsung.com',detail:'Smart home appliances'},{id:'Mitsubishi',name:'Mitsubishi',domain:'mitsubishielectric.com',detail:'Air conditioning'},{id:'AO Smith',name:'AO Smith',domain:'aosmithindia.com',detail:'Water heating'},{id:'Havells',name:'Havells',domain:'havells.com',detail:'Electrical appliances'},{id:'Voltas',name:'Voltas',domain:'voltas.com',detail:'Cooling solutions'},{id:'Lloyd',name:'Lloyd',domain:'mylloyd.com',detail:'Home appliances'}];
const APPLIANCES='https://www.sufyon.com/appliances.jpg',AC='https://dwecxxryy5p59.cloudfront.net/categories/d517f55e-ef8a-4dad-a7c6-0d837adbda5a',AC_PREMIUM='https://static.wixstatic.com/media/6a601d_73470571ae32476f93de247d7a7dc592~mv2.png/v1/fill/w_1536,h_1024,al_c,q_90/6a601d_73470571ae32476f93de247d7a7dc592~mv2.png',KITCHEN='https://www.ustabor.uz/upload/images/15230592_1910094765889127_2821130075351370746_n.jpg',SMALL='https://estilospe.vtexassets.com/arquivos/ids/3565486-800-800?aspect=true&height=800&v=638876789349070000&width=800';
export const PRODUCTS=[
{id:1,category:'Washing Machine',icon:'🫧',brand:'IFB',name:'Front Load Washing Machine',variant:'8 kg · Inverter · Front load',price:34990,mrp:41990,badge:'Popular',image:APPLIANCES},{id:2,category:'AC',icon:'❄️',brand:'Voltas',name:'Inverter Split AC',variant:'1.5 Ton · 5 Star',price:38990,mrp:45990,badge:'Cooling',image:AC},{id:3,category:'Refrigerator',icon:'🧊',brand:'Samsung',name:'Frost Free Refrigerator',variant:'Double door · Convertible',price:32990,mrp:38990,badge:'Smart choice',image:APPLIANCES},{id:4,category:'LED',icon:'📺',brand:'Samsung',name:'Crystal 4K Smart LED TV',variant:'55 inch · UHD · HDR',price:46990,mrp:57990,badge:'Bestseller',image:APPLIANCES},{id:5,category:'AC',icon:'❄️',brand:'Mitsubishi',name:'Heavy Duty Split AC',variant:'1.5 Ton · Inverter cooling',price:48990,mrp:55990,badge:'Premium',image:AC_PREMIUM},{id:6,category:'Microwave Oven',icon:'♨️',brand:'Panasonic',name:'Convection Microwave Oven',variant:'27 L · Auto Cook · Grill',price:14990,mrp:17990,badge:'Popular',image:KITCHEN},{id:7,category:'Iron',icon:'♨',brand:'Havells',name:'Steam Iron',variant:'Non-stick soleplate · Steam spray',price:2490,mrp:2990,badge:'Everyday',image:SMALL},{id:8,category:'Mixer Grinder',icon:'⚙️',brand:'Havells',name:'Mixer Grinder',variant:'750 W · 3 jars',price:4490,mrp:5490,badge:'Hot deal',image:SMALL},{id:9,category:'Washing Machine',icon:'🫧',brand:'Lloyd',name:'Top Load Washing Machine',variant:'7.5 kg · Fully automatic',price:20990,mrp:24990,badge:'Value',image:APPLIANCES},{id:10,category:'LED',icon:'📺',brand:'Lloyd',name:'4K Smart LED TV',variant:'43 inch · UHD · Smart TV',price:29990,mrp:35990,badge:'New',image:APPLIANCES},{id:11,category:'AC',icon:'❄️',brand:'Lloyd',name:'Inverter Split AC',variant:'1.5 Ton · 3 Star',price:34990,mrp:40990,badge:'Summer pick',image:AC},{id:12,category:'Refrigerator',icon:'🧊',brand:'Panasonic',name:'Double Door Refrigerator',variant:'Frost free · Inverter',price:36990,mrp:42990,badge:'Efficient',image:APPLIANCES},{id:13,category:'Microwave Oven',icon:'♨️',brand:'IFB',name:'Convection Microwave Oven',variant:'30 L · Rotisserie · Auto cook',price:16990,mrp:19990,badge:'Family pick',image:KITCHEN},{id:14,category:'AC',icon:'❄️',brand:'Samsung',name:'WindFree Inverter AC',variant:'1.5 Ton · Convertible cooling',price:42990,mrp:49990,badge:'Smart cooling',image:AC},{id:15,category:'Atta Chakki',icon:'🌾',brand:'Havells',name:'Domestic Atta Chakki',variant:'Automatic · Home flour mill',price:17990,mrp:20990,badge:'Home essential',image:KITCHEN},{id:16,category:'Water Heater',icon:'💧',brand:'AO Smith',name:'Instant Water Heater',variant:'Compact · Energy efficient',price:8990,mrp:10990,badge:'Hot water',image:SMALL}];
